### ISSUE TITLE
rocketchat install error

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-rocketchat#3]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by qiaofeng1227** [comment]
azure ubuntu20.04
```
TASK [role_common : pip upgrade(python2 support latest pip version is 20.3.4)] *****************************************************************************************************************************************************
fatal: [40.122.26.57]: FAILED! => {"changed": true, "cmd": "python2 -m pip install -U \"pip < 21.0\"", "delta": "0:00:00.014238", "end": "2021-05-15 02:46:23.491779", "msg": "non-zero return code", "rc": 1, "start": "2021-05-15 02:46:23.477541", "stderr": "/usr/bin/python2: No module named pip", "stderr_lines": ["/usr/bin/python2: No module named pip"], "stdout": "", "stdout_lines": []}

PLAY RECAP *************************************************************************************************************************************************************************************************************************
40.122.26.57 
```

**Comment by zengxc-1996** [comment]
![image](https://user-images.githubusercontent.com/63622990/118351709-03498500-b590-11eb-92fc-511e74643098.png)
Please change the Python interpreter to auto.

**Comment by qiaofeng1227** [comment]
azure ubuntu18.04
```
TASK [rocketchat : Wait mongodb restart and Use mongo shell initiate] ********************************************************************************************************************************************************************************************************
fatal: [23.99.130.100]: FAILED! => {"changed": true, "cmd": "sleep 60s \nmongo --eval \"printjson(rs.initiate())\"\n    \n", "delta": "0:01:00.288278", "end": "2021-05-15 08:24:50.854755", "msg": "non-zero return code", "rc": 1, "start": "2021-05-15 08:23:50.566477", "stderr": "exception: connect failed", "stderr_lines": ["exception: connect failed"], "stdout": "MongoDB shell version v4.0.24\nconnecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb\n2021-05-15T08:24:50.835+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :\nconnect@src/mongo/shell/mongo.js:356:17\n@(connect):2:6", "stdout_lines": ["MongoDB shell version v4.0.24", "connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb", "2021-05-15T08:24:50.835+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :", "connect@src/mongo/shell/mongo.js:356:17", "@(connect):2:6"]}

```

**Comment by zengxc-1996** [comment]
## Azure centos 7.9 install rocektchat error:
TASK [Install rocketchat] **************************************************************************************
fatal: [40.83.21.84]: FAILED! => {"changed": true, "cmd": "npm install", "delta": "0:00:29.344191", "end": "2021-05-17 03:27:07.069445", "msg": "non-zero return code", "rc": 1, "start": "2021-05-17 03:26:37.725254", "stderr": "npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future\nnpm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\nnpm WARN deprecated har-validator@5.1.5: this library is no longer supported\ngyp WARN EACCES current user (\"websoft9\") does not have permission to access the dev dir \"/root/.cache/node-gyp/12.22.1\"\ngyp WARN EACCES attempting to reinstall using temporary dev dir \"/data/wwwroot/bundle/programs/server/node_modules/fibers/.node-gyp\"\ngyp WARN install got an error, rolling back install\ngyp WARN install got an error, rolling back install\ngyp ERR! configure error \ngyp ERR! stack Error: EACCES: permission denied, mkdir '/data/wwwroot/bundle/programs/server/node_modules/fibers/.node-gyp'\ngyp ERR! System Linux 3.10.0-1160.15.2.el7.x86_64\ngyp ERR! command \"/opt/nvm/versions/node/v12.22.1/bin/node\" \"/opt/nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--release\"\ngyp ERR! cwd /data/wwwroot/bundle/programs/server/node_modules/fibers\ngyp ERR! node -v v12.22.1\ngyp ERR! node-gyp -v v5.1.0\ngyp ERR! not ok \nnode-gyp exited with code: 1\nPlease make sure you are using a supported platform and node version. If you\nwould like to compile fibers on this machine please make sure you have setup your\nbuild environment--\nWindows + OS X instructions here: https://github.com/nodejs/node-gyp\nUbuntu users please run: `sudo apt-get install g++ build-essential`\nRHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` \nAlpine users please run: `sudo apk add python make g++`\nsh: nodejs: command not found\nnpm ERR! code ELIFECYCLE\nnpm ERR! syscall spawn\nnpm ERR! file sh\nnpm ERR! errno ENOENT\nnpm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the fibers@4.0.3 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2021-05-17T03_27_07_038Z-debug.log", "stderr_lines": ["npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future", "npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142", "npm WARN deprecated har-validator@5.1.5: this library is no longer supported", "gyp WARN EACCES current user (\"websoft9\") does not have permission to access the dev dir \"/root/.cache/node-gyp/12.22.1\"", "gyp WARN EACCES attempting to reinstall using temporary dev dir \"/data/wwwroot/bundle/programs/server/node_modules/fibers/.node-gyp\"", "gyp WARN install got an error, rolling back install", "gyp WARN install got an error, rolling back install", "gyp ERR! configure error ", "gyp ERR! stack Error: EACCES: permission denied, mkdir '/data/wwwroot/bundle/programs/server/node_modules/fibers/.node-gyp'", "gyp ERR! System Linux 3.10.0-1160.15.2.el7.x86_64", "gyp ERR! command \"/opt/nvm/versions/node/v12.22.1/bin/node\" \"/opt/nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--release\"", "gyp ERR! cwd /data/wwwroot/bundle/programs/server/node_modules/fibers", "gyp ERR! node -v v12.22.1", "gyp ERR! node-gyp -v v5.1.0", "gyp ERR! not ok ", "node-gyp exited with code: 1", "Please make sure you are using a supported platform and node version. If you", "would like to compile fibers on this machine please make sure you have setup your", "build environment--", "Windows + OS X instructions here: https://github.com/nodejs/node-gyp", "Ubuntu users please run: `sudo apt-get install g++ build-essential`", "RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` ", "Alpine users please run: `sudo apk add python make g++`", "sh: nodejs: command not found", "npm ERR! code ELIFECYCLE", "npm ERR! syscall spawn", "npm ERR! file sh", "npm ERR! errno ENOENT", "npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`", "npm ERR! spawn ENOENT", "npm ERR! ", "npm ERR! Failed at the fibers@4.0.3 install script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /root/.npm/_logs/2021-05-17T03_27_07_038Z-debug.log"], "stdout": "\n> fibers@4.0.3 install /data/wwwroot/bundle/programs/server/node_modules/fibers\n> node build.js || nodejs build.js\n\n`linux-x64-72-glibc` exists; testing\nProblem with the binary; manual build incoming", "stdout_lines": ["", "> fibers@4.0.3 install /data/wwwroot/bundle/programs/server/node_modules/fibers", "> node build.js || nodejs build.js", "", "`linux-x64-72-glibc` exists; testing", "Problem with the binary; manual build incoming"]}

**Comment by zengxc-1996** [comment]
> ```
> TASK [rocketchat : Wait mongodb restart and Use mongo shell initiate] ********************************************************************************************************************************************************************************************************
> fatal: [23.99.130.100]: FAILED! => {"changed": true, "cmd": "sleep 60s \nmongo --eval \"printjson(rs.initiate())\"\n    \n", "delta": "0:01:00.288278", "end": "2021-05-15 08:24:50.854755", "msg": "non-zero return code", "rc": 1, "start": "2021-05-15 08:23:50.566477", "stderr": "exception: connect failed", "stderr_lines": ["exception: connect failed"], "stdout": "MongoDB shell version v4.0.24\nconnecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb\n2021-05-15T08:24:50.835+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :\nconnect@src/mongo/shell/mongo.js:356:17\n@(connect):2:6", "stdout_lines": ["MongoDB shell version v4.0.24", "connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb", "2021-05-15T08:24:50.835+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :", "connect@src/mongo/shell/mongo.js:356:17", "@(connect):2:6"]}
> ```

Use scripts instead of sleep.

**Comment by zengxc-1996** [comment]
## Mongo4.0 cannot be installed in Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/63622990/118429951-83452b80-b705-11eb-9c04-7ea0d0e4becc.png)

![image](https://user-images.githubusercontent.com/63622990/118430031-b5ef2400-b705-11eb-849c-9564396b2815.png)

**Comment by qiaofeng1227** [comment]
docker install

**Comment by reinethernal** [comment]
Docker only? So you won't do anything with bare-metal install?
